export const PLANS = [
  {
    plan_id: 1,
    name: "Free Plan",
    price: 0,
    invoice_limit: 10,
    client_limit: 5,
    product_listing_limit: 5,
    duration_days: 30,
    description: "Perfect for individuals to get started with basic invoicing.",
    features: {
      free_upgrade: true,
      data_security: true,
      track_expenses: true,
      custom_branding: true,
      qr_code_payments: true,
      unlimited_client: false,
      digital_signature: true,
      recurring_expense: false,
      recurring_invoice: false,
      unlimited_expense: true,
      unlimited_product: false,
      multi_device_login: true,
      inventory_management: true,
      multi_currency_support: true,
      reports_and_statements: true,
      track_invoice_payments: true,
      send_invoices_via_email: true,
      priority_customer_support: false,
      cloud_storage_for_invoices: false,
      multiple_invoice_templates: true,
      schedule_automatic_payment_reminders: false,
      send_unlimited_estimate_and_quotation: true,
      client_customization_as_per_requirement: false,
    },
  },
  {
    plan_id: 2,
    name: "Basic",
    price: 299,
    invoice_limit: 100,
    client_limit: 25,
    product_listing_limit: 1000,
    duration_days: 365,
    description: "Ideal for freelancers and small businesses.",
    features: {
      free_upgrade: true,
      data_security: true,
      track_expenses: true,
      custom_branding: true,
      qr_code_payments: true,
      unlimited_client: true,
      digital_signature: true,
      recurring_expense: false,
      recurring_invoice: false,
      unlimited_expense: true,
      unlimited_product: true,
      multi_device_login: true,
      inventory_management: true,
      multi_currency_support: true,
      reports_and_statements: true,
      track_invoice_payments: true,
      send_invoices_via_email: true,
      priority_customer_support: false,
      cloud_storage_for_invoices: true,
      multiple_invoice_templates: true,
      schedule_automatic_payment_reminders: false,
      send_unlimited_estimate_and_quotation: true,
      client_customization_as_per_requirement: false,
    },
  },
  {
    plan_id: 3,
    name: "Professional",
    price: 599,
    invoice_limit: 250,
    client_limit: 100,
    product_listing_limit: 3000,
    duration_days: 365,
    popular: true,
    description: "Best choice for growing businesses.",
    features: {
      free_upgrade: true,
      data_security: true,
      track_expenses: true,
      custom_branding: true,
      qr_code_payments: true,
      unlimited_client: true,
      digital_signature: true,
      recurring_expense: true,
      recurring_invoice: true,
      unlimited_expense: true,
      unlimited_product: true,
      multi_device_login: true,
      inventory_management: true,
      multi_currency_support: true,
      reports_and_statements: true,
      track_invoice_payments: true,
      send_invoices_via_email: true,
      priority_customer_support: false,
      cloud_storage_for_invoices: true,
      multiple_invoice_templates: true,
      schedule_automatic_payment_reminders: true,
      send_unlimited_estimate_and_quotation: true,
      client_customization_as_per_requirement: false,
    },
  },
  {
    plan_id: 4,
    name: "Enterprise",
    price: 899,
    invoice_limit: 1000,
    client_limit: 1000,
    product_listing_limit: 10000,
    duration_days: 365,
    description: "Complete solution for enterprises.",
    features: {
      free_upgrade: true,
      data_security: true,
      track_expenses: true,
      custom_branding: true,
      qr_code_payments: true,
      unlimited_client: true,
      digital_signature: true,
      recurring_expense: true,
      recurring_invoice: true,
      unlimited_expense: true,
      unlimited_product: true,
      multi_device_login: true,
      inventory_management: true,
      multi_currency_support: true,
      reports_and_statements: true,
      track_invoice_payments: true,
      send_invoices_via_email: true,
      priority_customer_support: true,
      cloud_storage_for_invoices: true,
      multiple_invoice_templates: true,
      schedule_automatic_payment_reminders: true,
      send_unlimited_estimate_and_quotation: true,
      client_customization_as_per_requirement: true,
    },
  },
];